services:
  server:
    image: newsletter-app
    restart: always
    expose:
      - 5000
    environment:
      MAIL_SERVER: smtp.strato.de
      MAIL_PORT: 587
      MAIL_USERNAME: no-reply@hacking-and-security.de
      MAIL_PASSWORD: bUpbem-dawme2-giszyf
    networks:
      - nginx
      - internal
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    networks:
      - internal
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  internal:
  nginx:
    external: true